config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :books
  devise_for :users

  root 'home#index'

  get 'ver_mais' => 'home#ver_mais_book'
  get 'index' => 'home#index'
  get 'destaques' => 'home#book_destaques'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category

  has_one_attached :image
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.destaque = false
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :selfLink, :imageLink, :language, :publisher, :publishedDate, :pageCount, :category_id, :image, :destaque)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'home'

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :selfLink %>
    <%= form.text_field :selfLink %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :imageLink %>
    <%= form.text_field :imageLink %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :publishedDate %>
    <%= form.date_select :publishedDate %>
  </div>

  <div class="field">
    <%= form.label :pageCount %>
    <%= form.number_field :pageCount %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= collection_select(:book, :category_id, Category.all, :id, :description) %>
  </div>

  <div class="field">
    <%= form.label :destaque %>
    <%= form.text_field :destaque %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Selflink</th>
      <th>Imagelink</th>
      <th>Language</th>
      <th>Publisher</th>
      <th>Publisheddate</th>
      <th>Pagecount</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.description %></td>
        <td><%= book.selfLink %></td>
        <td><%= image_tag book.image %><td>
        <td><%= book.imageLink %></td>
        <td><%= book.language %></td>
        <td><%= book.publisher %></td>
        <td><%= book.publishedDate %></td>
        <td><%= book.pageCount %></td>
        <td><%= book.category %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Biblioteca</title>

  </head>

  <body>

    <div>

      <header>

        <%= render  "/home/menu_sidebar" %>

        <div id="page-content-wrapper">

          <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <a href="../index" id="li-geral">Geral</a>
                <a href="../destaques" id="li-destaques">Livros em destaque</a>
              </ul>

              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <span class="glyphicon glyphicon-search btn-lg" id="span-search" aria-hidden="true"></span>
              </form>

            </div>

          </nav>

          <div class="content_book">

            <a href="/" class="glyphicon glyphicon-remove btn-lg btn_exit"></a>

            <td><%= image_tag @book.image, :size => "180x280", :class => 'ver_mais_image_book' %><td>

            <p>
              <h1 class="ver_mais_title"><%= @book.title %></h1>
            </p>

            <p>
              <h4 class="ver_mais_author"><%= @book.author %></h4>
            </p>

            <div class="ver_mais_likes"><span class='glyphicon glyphicon-star-empty btn-star btn-lg'></span> <span class='glyphicon glyphicon-star-empty btn-star btn-lg'></span> <span class='glyphicon glyphicon-star-empty btn-star btn-lg'></span> <span class='glyphicon glyphicon-star-empty btn-star btn-lg'></span> <span class='glyphicon glyphicon-star-empty btn-star btn-lg'></span></div>

            <p class="ver_mais_description">
              <%= @book.description %>
            </p>

            <div class="content_dados">

              <p class="ver_mais_linguagem">
                <strong>Linguagem:</strong>
                <%= @book.language %>
              </p>

              <p class="ver_mais_editora">
                <strong>Editora:</strong>
                <%= @book.publisher %>
              </p>

              <p class="ver_mais_publicacao">
                <strong>Data de publicação:</strong>
                <%= @book.publishedDate %>
              </p>

            </div>

            <div class="content_dados">

              <p class="ver_mais_paginas">
                <strong>Número de páginas:</strong>
                <%= @book.pageCount %>
              </p>

              <p>
                <a href="<%= @book.selfLink %>">Conferir preços</a>
              </p>

              <p class="ver_mais_categoria">
                <strong>Categoria:</strong>
                <%= @book.category.description %>
              </p>

            </div>

          </div>

        </div>
      
      </header>

    </div>

  </body>

</html>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render  "/home/menu_sidebar" %>

<div id="page-content-wrapper">

 <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <a href="../index" id="li-geral">Geral</a>
          <a href="../destaques" id="li-destaques">Livros em destaque</a>
          <li id="li-destaques" class="select_item_topbar"><%= @category.description %></li>
      </ul>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <span class="glyphicon glyphicon-search btn-lg" id="span-search" aria-hidden="true"></span>
      </form>

    </div>

 </nav>
      
  <div class="container-fluid">

    <div class="row">

      <% Book.all.each do |book| %>

        <% if book.category.description == @category.description %>

          <div class="card" style="width: 12em">

            <div class="card-body">

              <%= image_tag(book.image, :alt => "", :size => "150x220", :class => 'image-book') %>
                  
              <br>

              <span class="glyphicon glyphicon-info-sign btn-custom btn-lg" aria-hidden="true" data-toggle="popover" title="<strong><%= book.title %></strong>" data-content="<strong><%= book.author %></strong><br><%= book.description %>"></span>

              <div class="div-buttons">

                <span class="glyphicon glyphicon-thumbs-up button-like btn-lg" aria-hidden="true"></span>
                <span class="glyphicon glyphicon glyphicon-book button-checked btn-lg" aria-hidden="true"></span>
                <%= link_to book.title, book, :class => 'ver_mais'%>

              </div>

              <h2 class="card-title"><%= book.title %></h2>
              <p class="card-text"><%= book.author %></p>

            </div>

          </div>

        <% end %>

      <% end %>

    </div>

  </div>

</div>

app/views/home/_menu_sidebar.html.erb
<div class="d-flex" id="wrapper">

  <div class="bg-light border-right" id="sidebar-wrapper">

    <div class="sidebar-heading">

      <p id="title-menu">L</p>

    </div>

    <div class="list-group list-group-flush" id="itensDiv">

      <a class="nav-link dropdown-toggle list-group-item-action bg-light" id="dropdown-menu" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categorias</a>
      
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

        <% Category.all.each do |categoria| %>

          <a class="dropdown-item" href="#"><%= link_to categoria.description, categoria %></a>
          
        <% end %>

      </div>

      <% if user_signed_in? %>
        <a href="#" class="list-group-item list-group-item-action bg-light itemMenu">Minha coleção</a>
        <strong><p class="home_email"><%= current_user.email %></p></strong>
        <%= link_to "", edit_user_registration_path, :class => 'glyphicon glyphicon-user btn-lg edit' %>
        <%= link_to "", destroy_user_session_path, method: :delete, :class => 'glyphicon glyphicon-arrow-left btn-lg log_out' %>
      <% else %>
        <strong><%= link_to "Sign_up", new_user_registration_path, :class => 'sign_up'  %></strong>
        <strong><%= link_to "Login", new_user_session_path, :class => 'sign_in'  %></strong>
      <% end %>
      
  </div>

</div>

app/views/home/book_destaques.html.erb
<!DOCTYPE html>
<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Biblioteca</title>

  </head>

  <body>

    <div>

      <header>

        <%= render  "menu_sidebar" %>

        <div id="page-content-wrapper">

          <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li id="li-geral" class="x">Geral</li>
                <li id="li-destaques" class="select_item_topbar">Livros em destaque</li>
              </ul>

              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <span class="glyphicon glyphicon-search btn-lg" id="span-search" aria-hidden="true"></span>
              </form>

            </div>

          </nav>

          <div class="container-fluid">

            <div class="row">

              <% Book.all.each do |book| %>

                <% if book.destaque == 'true' %>

                  <%= book.destaque %>

                  <div class="card" style="width: 12em">

                    <div class="card-body">

                      <%= image_tag(book.image, :alt => "", :size => "150x220", :class => 'image-book') %>

                      <br>

                      <span class="glyphicon glyphicon-info-sign btn-custom btn-lg" aria-hidden="true" data-toggle="popover" title="<strong><%= book.title %></strong>" data-content="<strong><%= book.author %></strong><br><%= book.description %>"></span>

                      <div class="div-buttons">

                        <span class="glyphicon glyphicon-thumbs-up button-like btn-lg" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon glyphicon-book button-checked btn-lg" aria-hidden="true"></span>
                        <%= link_to book.title, book, :class => 'ver_mais'%>

                      </div>

                      <h2 class="card-title"><%= book.title %></h2>
                      <p class="card-text"><%= book.author %></p>

                    </div>

                  </div>

                <% end %>

              <% end %>
              
            </div>

          </div>

        </div>
      
      </header>

    </div>

  </body>

</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Biblioteca</title>

  </head>

  <body>

    <div>

      <header>

        <%= render  "menu_sidebar" %>

        <div id="page-content-wrapper">

          <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li id="li-geral" class="select_item_topbar">Geral</li>
                <li id="li-destaques" class="x">Livros em destaque</li>
              </ul>

              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <span class="glyphicon glyphicon-search btn-lg" id="span-search" aria-hidden="true"></span>
              </form>

            </div>

          </nav>
          
          <div class="container-fluid">

            <div class="row">

              <% Book.all.each do |book| %>

                <div class="card" style="width: 12em">

                  <div class="card-body">

                    <%= image_tag(book.image, :alt => "", :size => "150x220", :class => 'image-book') %>
                    
                    <br>

                    <span class="glyphicon glyphicon-info-sign btn-custom btn-lg" aria-hidden="true" data-toggle="popover" title="<strong><%= book.title %></strong>" data-content="<strong><%= book.author %></strong><br><%= book.description %>"></span>

                    <div class="div-buttons">

                      <% if user_signed_in? %>
                        <span class="glyphicon glyphicon-thumbs-up button-like btn-lg" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-book button-checked btn-lg" aria-hidden="true"></span>
                        <%= link_to book.title, book, :class => 'ver_mais'%>
                      <% else %>
                        <span class="glyphicon glyphicon-thumbs-up button-like btn-lg" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-book button-checked btn-lg" aria-hidden="true"></span>
                        <a class="ver_mais"><%= book.title %></a>
                      <% end %>

                    </div>

                    <h2 class="card-title"><%= book.title %></h2>
                    <p class="card-text"><%= book.author %></p>

                  </div>

                </div>

              <% end %>

            </div>

          </div>

        </div>
      
      </header>

    </div>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibliotecca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibliotecca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'home', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %> -->

    <%= yield %>
  </body>
</html>